# Generated by Django 6.0.2 on 2026-05-07 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_busqueda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'query')},
            },
        ),
        migrations.CreateModel(
            name='PlantasFavoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_planta_api', models.PositiveIntegerField()),
                ('nombre_comun', models.CharField(max_length=150)),
                ('nombre_cientifico', models.CharField(max_length=150)),
                ('imagen', models.URLField(blank=True, max_length=1000)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-agregado'],
                'unique_together': {('usuario', 'id_planta_api')},
            },
        ),
    ]
