# Generated by Django 6.0.2 on 2026-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.CharField(max_length=500)),
                ('idioma_objetivo', models.CharField(max_length=10)),
                ('traduccion', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('texto_original', 'idioma_objetivo')},
            },
        ),
    ]
