# Generated by Django 6.0.2 on 2026-06-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_traducciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_planta_api', models.PositiveIntegerField(unique=True)),
                ('nombre_comun', models.CharField(max_length=250)),
                ('nombre_cientifico', models.CharField(max_length=250)),
                ('tipo', models.CharField(blank=True, max_length=150, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=150, null=True)),
                ('riego', models.CharField(blank=True, max_length=150, null=True)),
                ('luz', models.CharField(blank=True, max_length=150, null=True)),
                ('crecimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('mantenimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('venenosa_humano', models.BooleanField(null=True)),
                ('venenosa_mascota', models.BooleanField(null=True)),
                ('imagen', models.URLField(blank=True)),
                ('datos_api', models.JSONField(default=dict)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('datos_completos', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre_cientifico'],
            },
        ),
        migrations.AlterField(
            model_name='plantasfavoritas',
            name='nombre_cientifico',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='plantasfavoritas',
            name='nombre_comun',
            field=models.CharField(max_length=250),
        ),
    ]
