# Generated by Django 6.0.2 on 2026-06-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_plantas_alter_plantasfavoritas_nombre_cientifico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantas',
            old_name='id_planta_api',
            new_name='id_planta_perenual',
        ),
    ]
