# Generated by Django 6.0.2 on 2026-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_rename_id_planta_api_plantas_id_planta_perenual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='imagen',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
